- name: "INSTALL PSQLv16"
  block:
  - name: »» Installing packages
    apt: name="postgresql-16" state=latest      

  - name: »» Adding credentials to the password.info file
    include_role:
      name: utils/add-credentials
      public: yes
    vars:
      app: "PostgreSQL"
      login: "postgres"
      pwd: "postgres"
  become: true    