# This is the network config written by 'isard-scripts' (https://github.com/FherStk/isard-scripts)
network:
  version: 2
  ethernets:
    #default (internet access only)
    enp1s0:
      dhcp4: true
      dhcp-identifier: mac
    #wireguardVPN (private VPN between IsardVDI and an external computer)
    enp2s0:
      dhcp4: true
      dhcp-identifier: mac
      optional: true
    #personal (private network between IsardVDI machines)
    enp3s0:
      dhcp4: no
      addresses: [x.x.x.x/yy]
      optional: true