- name: "Isard-Scripts: installing at the local system"
  hosts: localhost

  tasks:
  - name: VARIABLES
    block:
    - name: » Loading global variables
      set_fact: user="{{ ansible_facts['user_id'] }}"
    - set_fact: pwd="{{ ansible_become_password }}"
    - set_fact: install_path="{{ playbook_dir }}/.."
    - name: » Creating config directory
      file:
        path: /etc/isard-scripts/config
        state: directory
        mode: '0755'
      become: true
    - name: » Storing main password
      copy:
        content: "{{ ansible_become_password }}"
        dest: /etc/isard-scripts/config/main-password
        mode: '0600'
        owner: root
        group: root
      become: true
      no_log: true
    - set_fact: run_script="sudo bash {{ install_path }}/run.sh"

  - name: NETWORK SETUP
    block:
    - name: » Setting up the network intefaces
      include_role:
        name: utils/netplan-apply
        public: yes
      vars:
        personal1Config: "dhcp"
        groupNetwork1Config: "dhcp"

  - name: UPGRADE PACKAGES (ALSO DISABLES AUTOMATIC UPGRADES)
    block:
    - name: » Disabling automatic upgrades
      apt: name="unattended-upgrades" state=absent
      become: true

    - name: » Upgrading installed packages
      include_role:
        name: utils/upgrade-packages
        public: yes

  - name: INSTALL DEPENDENCIES
    block:
    - name: » Installing dependencies
      apt: name={{ item }} state=latest
      loop: [curl,openssh-server,imagemagick]
    become: true

  - name: AUTOLOGIN (SERVER)
    when: "'XDG_CURRENT_DESKTOP' not in ansible_facts['env']"
    block:
    - name: » Enabling autologin for the current user (Ubuntu Server)
      file: path="/etc/systemd/system/getty@tty1.service.d" state=directory
    - copy:
        dest: "/etc/systemd/system/getty@tty1.service.d/override.conf"
        content: |
          [Service]
          ExecStart=
          ExecStart=-/sbin/agetty --noissue --autologin {{ user }} %I $TERM
          Type=idle
    become: true

  - name: AUTOLOGIN (DESKTOP)
    when: "'XDG_CURRENT_DESKTOP' in ansible_facts['env'] and 'GNOME' in ansible_facts['env'].XDG_CURRENT_DESKTOP"
    block:
    - name: » Enabling autologin for the current user (Ubuntu Desktop)
      copy:
        dest: "/etc/gdm3/custom.conf"
        content: |
          [daemon]
          AutomaticLoginEnable=true
          AutomaticLogin={{ user }}
    become: true

  - name: GNOME FAVORITES (DESKTOP)
    when: "'XDG_CURRENT_DESKTOP' in ansible_facts['env'] and 'GNOME' in ansible_facts['env'].XDG_CURRENT_DESKTOP"
    block:
    - name: » Setting GNOME favorites
      shell: >
        gsettings set org.gnome.shell favorite-apps
        "['firefox_firefox.desktop', 'org.gnome.Nautilus.desktop', 'org.gnome.Ptyxis.desktop']"
      environment:
        DBUS_SESSION_BUS_ADDRESS: "unix:path=/run/user/{{ ansible_facts['user_uid'] }}/bus"

  - name: "DISABLE SUDO PASSWORD"
    block:
    - name: » Removing the sudo password request for the current user
      copy:
        dest: "/etc/sudoers.d/nopass"
        content: "{{ user }} ALL=(ALL) NOPASSWD:ALL\n"
        owner: root
        group: root
        mode: "0400"
      become: true

  - name: "AUTOSTART ON NEXT BOOT (SERVER)"
    when: "'XDG_CURRENT_DESKTOP' not in ansible_facts['env']"
    block:
    - name: » Setting up the script startup on next boot (Ubuntu Server)
      lineinfile:
        line: "{{ run_script }}"
        dest: "/home/{{ user }}/.profile"

  - name: "AUTOSTART ON NEXT BOOT (DESKTOP)"
    when: "'XDG_CURRENT_DESKTOP' in ansible_facts['env'] and 'GNOME' in ansible_facts['env'].XDG_CURRENT_DESKTOP"
    block:
    - name: » Setting up the script startup on next boot (Ubuntu Desktop)
      set_fact: autostart="/home/{{ user }}/.config/autostart"
    - set_fact: desktop_file="{{ autostart }}/isard-scripts.desktop"
    - set_fact: launcher_file="{{ autostart }}/isard-scripts-runner.sh"
    - file: path="{{ autostart }}" state=directory
    - copy:
        dest: "{{ launcher_file }}"
        mode: "0755"
        content: |
          #!/bin/bash
          {{ run_script }}
    - copy:
        dest: "{{ desktop_file }}"
        content: |
          [Desktop Entry]
          Type=Application
          Path={{ install_path }}
          Exec=ptyxis --maximize -- {{ launcher_file }}
          Hidden=false
          NoDisplay=false
          X-GNOME-Autostart-enabled=true
          Name[en_NG]=Terminal
          Name=Terminal
          Comment[en_NG]=Start Isard-Scripts On Startup
          Comment=Start Isard-Scripts On Startup

  - name: CREDENTIALS
    block:
    - name: » Setting up the credentials file
      set_fact: passwords_file="/home/{{ user }}/passwords.info"
    - copy:
        dest: "{{ passwords_file }}"
        content: |
          #########################
          #   SYSTEM CREDENTIALS   #
          #########################
        force: yes
        mode: "0600"

    - name: » Adding credentials to the password.info file
      include_role:
        name: utils/add-credentials
        public: yes
      vars:
        app: "Ubuntu"
        login: "{{ user }}"

    - name: » Building the credentials background / prompt
      include_role:
        name: utils/store-credentials
        public: yes

  - name: CLEANING
    block:
    - name: » Cleaning
      shell: cat /dev/null > /home/{{ user }}/.bash_history
