- name: "Isard-Scripts: select how to setup the local system"
  hosts: localhost
  vars_prompt:
  - name: software
    prompt: |1
      Please, write down (comma separated) the numbers corresponding to the actions that shall be performed:
      1) basic-setup
      2) psql-v18: install
      3) psql-v18: setup remote connections
      4) psql-v18: setup the 'employees-lite' database
      5) dmoj-v4 [WARNING: ON DEVELOPEMENT!]
    private: no

  - name: hname
    prompt: "Please, write down the host name for the current system:\n"
    private: no
    default: "ubuntu"

  - name: networkConfig
    prompt: "Please, write down an static IP address for the 'Personal1' network, or type 'dhcp' if you want to setup a dynamic address:\n"
    private: no
    default: "192.168.1.1/24"

  tasks:
  - name: VARIABLES
    block:
    - name: » Loading global variables
      set_fact: user="{{ ansible_facts['user_id'] }}"
    - set_fact: pwd="{{ ansible_become_password }}"

  - name: READING OPTIONS
    block:
    - name: » Reading the selected options to setup
      set_fact:
        options: "{{ software.split(',') }}"
        passwords_file: "/home/{{ user }}/passwords.info"

  - name: HOSTNAME
    block:
    - name: » Setting up the hostname
      hostname:
        name: "{{ hname }}"
      become: true

  - name: NETWORK SETUP
    block:
    - name: » Setting up the network intefaces
      include_role:
        name: utils/netplan-apply
        public: yes

  - name: UPGRADE PACKAGES
    when: "'1' not in options"
    block:
    - name: » Upgrading installed packages
      include_role:
        name: utils/upgrade-packages
        public: yes

  - name: SETUP OPTION 2
    when: "'2' in options"
    block:
    - name: » PostgreSQL v18 (install)
      include_role:
        name: apps/psql-v18-install
        public: yes

  - name: SETUP OPTION 3
    when: "'3' in options"
    block:
    - name: » PostgreSQL v18 (setup remote connections)
      include_role:
        name: apps/psql-v18-remote
        public: yes

  - name: SETUP OPTION 4
    when: "'4' in options"
    block:
    - name: » PostgreSQL v18 (setup the 'employees-lite' database)
      include_role:
        name: apps/psql-v18-bbdd-employees-lite
        public: yes

  - name: SETUP OPTION 5
    when: "'5' in options"
    block:
    - name: » DMOJ v4
      include_role:
        name: apps/dmoj-v4
        public: yes

  - name: CREDENTIALS
    when: "'1' not in options"
    block:
    - name: » Building the credentials background / prompt
      include_role:
        name: utils/store-credentials
        public: yes

  - name: CLEANING
    block:
    - name: » Cleaning
      file: path="/home/{{ user }}/.config/autostart/isard-scripts.desktop" state=absent
    - lineinfile:
        path: /home/{{ user }}/.profile
        regexp: '^sudo bash {{ playbook_dir }}/../run.sh'
        state: absent
    - shell: cat /dev/null > /home/{{ user }}/.bash_history

  - name: REBOOT
    block:
    - name: » Rebooting the system
      command: shutdown -r now
      become: true
      async: 1
      poll: 0
